### ISSUE TITLE
How to test the VGG?

### ISSUE THREAD

**Issue by zhukaikang** [walsvid/VGG-TensorFlow#1]
i'm using your code to train the VGGNet on TensorFlow . Your work is really impressive, but i have a question about how to test the VGGNet. It seems like you have not added the test part to the code. Do i have to write it myself? Or maybe i just didn't notice the test part.. i really appreciate you or someone else can answer it.

**Comment by walsvid** [comment]
I'll release the code of test part as soon as possible, thanks for your reply. Hope this repository can help you.

**Comment by walsvid** [comment]
Hi, @zhukaikang I have already release the code of test. You can use `test.py` to test a image.  As for
test a image using trained model ( in tensorflow called `checkpoint`), you can simply use triain saver to restore the checkpoint. And then build the network and inference it.
If you have other questions please contact me.
